export const ApiConstant = {
  customer: "http://localhost:8080/api/v1/customer",
  customer2: "http://localhost:8081/api/v1/user",
  employee: "http://localhost:8080/api/v1/employee",
  product: "http://localhost:8080/api/v1/product",
  product2: "http://localhost:8081/api/v1/product",
  category: "http://localhost:8080/api/v1/category",
  category2: "http://localhost:8081/api/v1/category",
  productImage: 'http://localhost:8080/api/v1/productImage',
  productDetail: 'http://localhost:8080/api/v1/productDetail',
  productDetail2: 'http://localhost:8081/api/v1/productDetail',
  size: 'http://localhost:8080/api/v1/size',
  color: 'http://localhost:8080/api/v1/color',
  order: 'http://localhost:8080/api/v1/order',
  orderDetail: 'http://localhost:8080/api/v1/orderDetail',
  ghn: 'https://dev-online-gateway.ghn.vn/shiip/public-api/v2/shipping-order',
  contact: 'http://localhost:8080/api/v1/contact',
  cloudinary: 'http://localhost:8080/api/image',
  auth: {
        login: 'http://localhost:8080/api/auth/admin/login',
    },
  api:"http://localhost:8080/api/v1/",
  // login: 'http://localhost:8080/api/auth/admin/login',
  rating: 'http://localhost:8080/api/v1/rating',
  ratingImg: 'http://localhost:8080/api/v1/rating-images' ,
  statiscal: 'http://localhost:8080/api/v1/statiscal' ,
  promotion: 'http://localhost:8080/api/v1/discount' ,
  promotionProduct: 'http://localhost:8080/api/v1/discount_product'
};
